/**
 ******************************************************************************
 *
 * @file       examplesettings.h
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Implementation of the ExampleSettings object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: examplesettings.xml. 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef EXAMPLESETTINGS_H
#define EXAMPLESETTINGS_H

#include "openpilot.h"

// Object constants
#define EXAMPLESETTINGS_OBJID 3555345034U
#define EXAMPLESETTINGS_NAME "ExampleSettings"
#define EXAMPLESETTINGS_ISSINGLEINST 1
#define EXAMPLESETTINGS_ISSETTINGS 1
#define EXAMPLESETTINGS_NUMBYTES sizeof(ExampleSettingsData)

// Data access macros
#define ExampleSettingsGet(dataOut) UAVObjGetData(ExampleSettingsGetHandle(), dataOut)
#define ExampleSettingsSet(dataIn) UAVObjSetData(ExampleSettingsGetHandle(), dataIn)

// Object data
typedef struct {
    int8_t setting1;
    int16_t setting2;
    int8_t setting3;
    int32_t setting4;

} __attribute__((packed)) ExampleSettingsData;

// Enumeration types


// Generic interface functions
int32_t ExampleSettingsInitialize();
UAVObjHandle ExampleSettingsGetHandle();

#endif // EXAMPLESETTINGS_H
