/**
 ******************************************************************************
 * @addtogroup UAVObjects OpenPilot UAVObjects
 * @{ 
 * @addtogroup FlightSituationActual FlightSituationActual 
 * @brief Currently unused
 *
 * Autogenerated files and functions for FlightSituationActual Object
 
 * @{ 
 *
 * @file       flightsituationactual.h
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Implementation of the FlightSituationActual object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: flightsituationactual.xml. 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef FLIGHTSITUATIONACTUAL_H
#define FLIGHTSITUATIONACTUAL_H

// Object constants
#define FLIGHTSITUATIONACTUAL_OBJID 499301246U
#define FLIGHTSITUATIONACTUAL_NAME "FlightSituationActual"
#define FLIGHTSITUATIONACTUAL_METANAME "FlightSituationActualMeta"
#define FLIGHTSITUATIONACTUAL_ISSINGLEINST 1
#define FLIGHTSITUATIONACTUAL_ISSETTINGS 0
#define FLIGHTSITUATIONACTUAL_NUMBYTES sizeof(FlightSituationActualData)

// Object access macros
/**
 * @function FlightSituationActualGet(dataOut)
 * @brief Populate a FlightSituationActualData object
 * @param[out] dataOut 
 */
#define FlightSituationActualGet(dataOut) UAVObjGetData(FlightSituationActualHandle(), dataOut)
#define FlightSituationActualSet(dataIn) UAVObjSetData(FlightSituationActualHandle(), dataIn)
#define FlightSituationActualInstGet(instId, dataOut) UAVObjGetInstanceData(FlightSituationActualHandle(), instId, dataOut)
#define FlightSituationActualInstSet(instId, dataIn) UAVObjSetInstanceData(FlightSituationActualHandle(), instId, dataIn)
#define FlightSituationActualConnectQueue(queue) UAVObjConnectQueue(FlightSituationActualHandle(), queue, EV_MASK_ALL_UPDATES)
#define FlightSituationActualConnectCallback(cb) UAVObjConnectCallback(FlightSituationActualHandle(), cb, EV_MASK_ALL_UPDATES)
#define FlightSituationActualCreateInstance() UAVObjCreateInstance(FlightSituationActualHandle())
#define FlightSituationActualRequestUpdate() UAVObjRequestUpdate(FlightSituationActualHandle())
#define FlightSituationActualRequestInstUpdate(instId) UAVObjRequestInstanceUpdate(FlightSituationActualHandle(), instId)
#define FlightSituationActualUpdated() UAVObjUpdated(FlightSituationActualHandle())
#define FlightSituationActualInstUpdated(instId) UAVObjUpdated(FlightSituationActualHandle(), instId)
#define FlightSituationActualGetMetadata(dataOut) UAVObjGetMetadata(FlightSituationActualHandle(), dataOut)
#define FlightSituationActualSetMetadata(dataIn) UAVObjSetMetadata(FlightSituationActualHandle(), dataIn)
#define FlightSituationActualReadOnly(dataIn) UAVObjReadOnly(FlightSituationActualHandle())

// Object data
typedef struct {
    float Latitude;
    float Longitude;
    float Altitude;
    float ATG;
    float Climbrate;
    float Heading;
    float Airspeed;
    float Course;
    float Groundspeed;

} __attribute__((packed)) FlightSituationActualData;

// Field information
// Field Latitude information
// Field Longitude information
// Field Altitude information
// Field ATG information
// Field Climbrate information
// Field Heading information
// Field Airspeed information
// Field Course information
// Field Groundspeed information


// Generic interface functions
int32_t FlightSituationActualInitialize();
UAVObjHandle FlightSituationActualHandle();

#endif // FLIGHTSITUATIONACTUAL_H

/**
 * @}
 * @}
 */