/**
 ******************************************************************************
 * @addtogroup UAVObjects OpenPilot UAVObjects
 * @{ 
 * @addtogroup PipXtremeModemStatus PipXtremeModemStatus 
 * @brief Status for the @ref PipXtremeModem
 *
 * Autogenerated files and functions for PipXtremeModemStatus Object
 
 * @{ 
 *
 * @file       pipxtrememodemstatus.h
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Implementation of the PipXtremeModemStatus object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: pipxtrememodemstatus.xml. 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef PIPXTREMEMODEMSTATUS_H
#define PIPXTREMEMODEMSTATUS_H

// Object constants
#define PIPXTREMEMODEMSTATUS_OBJID 539085060U
#define PIPXTREMEMODEMSTATUS_NAME "PipXtremeModemStatus"
#define PIPXTREMEMODEMSTATUS_METANAME "PipXtremeModemStatusMeta"
#define PIPXTREMEMODEMSTATUS_ISSINGLEINST 1
#define PIPXTREMEMODEMSTATUS_ISSETTINGS 0
#define PIPXTREMEMODEMSTATUS_NUMBYTES sizeof(PipXtremeModemStatusData)

// Object access macros
/**
 * @function PipXtremeModemStatusGet(dataOut)
 * @brief Populate a PipXtremeModemStatusData object
 * @param[out] dataOut 
 */
#define PipXtremeModemStatusGet(dataOut) UAVObjGetData(PipXtremeModemStatusHandle(), dataOut)
#define PipXtremeModemStatusSet(dataIn) UAVObjSetData(PipXtremeModemStatusHandle(), dataIn)
#define PipXtremeModemStatusInstGet(instId, dataOut) UAVObjGetInstanceData(PipXtremeModemStatusHandle(), instId, dataOut)
#define PipXtremeModemStatusInstSet(instId, dataIn) UAVObjSetInstanceData(PipXtremeModemStatusHandle(), instId, dataIn)
#define PipXtremeModemStatusConnectQueue(queue) UAVObjConnectQueue(PipXtremeModemStatusHandle(), queue, EV_MASK_ALL_UPDATES)
#define PipXtremeModemStatusConnectCallback(cb) UAVObjConnectCallback(PipXtremeModemStatusHandle(), cb, EV_MASK_ALL_UPDATES)
#define PipXtremeModemStatusCreateInstance() UAVObjCreateInstance(PipXtremeModemStatusHandle())
#define PipXtremeModemStatusRequestUpdate() UAVObjRequestUpdate(PipXtremeModemStatusHandle())
#define PipXtremeModemStatusRequestInstUpdate(instId) UAVObjRequestInstanceUpdate(PipXtremeModemStatusHandle(), instId)
#define PipXtremeModemStatusUpdated() UAVObjUpdated(PipXtremeModemStatusHandle())
#define PipXtremeModemStatusInstUpdated(instId) UAVObjUpdated(PipXtremeModemStatusHandle(), instId)
#define PipXtremeModemStatusGetMetadata(dataOut) UAVObjGetMetadata(PipXtremeModemStatusHandle(), dataOut)
#define PipXtremeModemStatusSetMetadata(dataIn) UAVObjSetMetadata(PipXtremeModemStatusHandle(), dataIn)
#define PipXtremeModemStatusReadOnly(dataIn) UAVObjReadOnly(PipXtremeModemStatusHandle())

// Object data
typedef struct {
    uint32_t Serial_Number;
    uint32_t Up_Time;
    uint32_t Frequency;
    uint32_t RF_Bandwidth;
    int8_t Tx_Power;
    uint8_t State;
    uint16_t Tx_Retry;
    uint32_t Tx_Data_Rate;
    uint32_t Rx_Data_Rate;

} __attribute__((packed)) PipXtremeModemStatusData;

// Field information
// Field Serial_Number information
// Field Up_Time information
// Field Frequency information
// Field RF_Bandwidth information
// Field Tx_Power information
// Field State information
/* Enumeration options for field State */
typedef enum { PIPXTREMEMODEMSTATUS_STATE_DISCONNECTED=0, PIPXTREMEMODEMSTATUS_STATE_CONNECTING=1, PIPXTREMEMODEMSTATUS_STATE_CONNECTED=2, PIPXTREMEMODEMSTATUS_STATE_NOTREADY=3 } PipXtremeModemStatusStateOptions;
// Field Tx_Retry information
// Field Tx_Data_Rate information
// Field Rx_Data_Rate information


// Generic interface functions
int32_t PipXtremeModemStatusInitialize();
UAVObjHandle PipXtremeModemStatusHandle();

#endif // PIPXTREMEMODEMSTATUS_H

/**
 * @}
 * @}
 */
