TEMPLATE = subdirs
CONFIG += ordered
SUBDIRS = core
SUBDIRS += internals
SUBDIRS += mapwidget
#SUBDIRS +=teste
#SUBDIRS +=gettilestest
#SUBDIRS +=widgettest
#SUBDIRS +=opmapplugin
SUBDIRS+=finaltest
