include(../../plugins/coreplugin/coreplugin.pri)
include(../../libs/utils/utils.pri)
include(../../plugins/uavobjects/uavobjects.pri)
include(../uavobjectutil/uavobjectutil.pri)
include(../uavsettingsimportexport/uavsettingsimportexport.pri)
include(../uavtalk/uavtalk.pri)
