#
# MacOSX-specific packaging
#

gcs: uavobjects
	$(V1) $(MAKE) -C $(ROOT_DIR) GCS_BUILD_CONF=release $@

ground_package: | gcs

package: release_ground release_flight 
	$(ROOT_DIR)/release/osx/package

release: | package 

.PHONY: gcs ground_package
