#
# MacOSX-specific packaging
#

package: gcs release_flight
	( \
	  ROOT_DIR="$(ROOT_DIR)" \
	  BUILD_DIR="$(BUILD_DIR)" \
	  RELEASE_LBL="$(RELEASE_LBL)" \
	  RELEASE_DIR="$(RELEASE_DIR)" \
	  FW_DIR="$(FW_DIR)" \
	  "$(ROOT_DIR)/release/osx/package" \
	)

gcs: uavobjects
	$(V1) $(MAKE) -C $(ROOT_DIR) GCS_BUILD_CONF=release $@

ground_package: | package

.PHONY: gcs ground_package package
