#ifndef PIOS_USBHOOK_H
#define PIOS_USBHOOK_H

typedef enum _HID_REQUESTS {
	GET_REPORT = 1,
	GET_IDLE,
	GET_PROTOCOL,

	SET_REPORT = 9,
	SET_IDLE,
	SET_PROTOCOL
} HID_REQUESTS;

typedef enum CDC_REQUESTS {
	SET_LINE_CODING = 0x20,
	GET_LINE_CODING = 0x21,
	SET_CONTROL_LINE_STATE = 0x23,
} CDC_REQUESTS;

#endif /* PIOS_USBHOOK_H */

