Document: openpilot
Title: Debian openpilot Manual
Author: <insert document author here>
Abstract: This manual describes what openpilot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openpilot/openpilot.sgml.gz

Format: postscript
Files: /usr/share/doc/openpilot/openpilot.ps.gz

Format: text
Files: /usr/share/doc/openpilot/openpilot.text.gz

Format: HTML
Index: /usr/share/doc/openpilot/html/index.html
Files: /usr/share/doc/openpilot/html/*.html
