/**
 ******************************************************************************
 *
 * @file       exampleobject.h
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Implementation of the ExampleObject object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: exampleobject.xml. 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/* 
 * This program is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation; either version 3 of the License, or 
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 * 
 * You should have received a copy of the GNU General Public License along 
 * with this program; if not, write to the Free Software Foundation, Inc., 
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
#ifndef EXAMPLEOBJECT_H
#define EXAMPLEOBJECT_H

#include "uavdataobject.h"

class ExampleObject: public UAVDataObject
{
public:   
    typedef struct {
        qint8 field1;
        qint16 field2;
        float field3[4];
        qint32 field4;

    } __attribute__((packed)) DataFields;
  
    static const quint32 OBJID = 3048370380U;
    static const QString NAME;
    static const bool SINGLEINST = 0;
    static const quint32 NUMBYTES = sizeof(DataFields);

    ExampleObject();

    DataFields getData();
    void setData(DataFields& data);
    Metadata getDefaultMetadata();
    UAVDataObject* clone(quint32 instID);
	
private:
    DataFields data;

};

#endif // EXAMPLEOBJECT_H
